### ISSUE TITLE
How to pass options to picom

### ISSUE THREAD

**Issue by villqrd** [regolith-linux/regolith-compositor-picom-glx#5]
Hello, thanks for the great work!

I would like to know how to pass options to picom? Specifically, I would like to add `--experimental-backends` flag.

**Comment by kgilmer** [comment]
Hi @villqrd , this has been recently asked by another person but I cannot find the issue.  For your situation, I believe this flag must be passed as a parameter to `picom` during launch rather than being added to the config file itself.  Due to this, you cannot just create a user version of the `picom` config.  Rather, you'll need to update the Regolith `picom` init script that is launched from i3.  The init script lives in `/usr/share/regolith-compositor/init`.  You can edit the file and add the additional parameter.  You'll need to log back in for the changes to take effect.

**Comment by villqrd** [comment]
@kgilmer This is exactly what I was looking for, thank you!
